# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: { python-version: 3.8 }
      - name: Install poetry
        uses: Gr1N/setup-poetry@v4
      - name: Install dependencies
        run: poetry install
      - name: Lint with flake8
        run: poetry run flake8 tap_sklik tests
      - name: Test with pytest
        run: poetry run pytest
        env: { SKLIK_TEST_TOKEN: "${{ secrets.SKLIK_TEST_TOKEN }}" }
      - name: Build tarball
        run: poetry build
      # see https://github.com/actions/upload-artifact#zipped-artifact-downloads
      - name: Untar package
        run: cd dist && tar -tvf *.tar.gz
      - name: Archive tarball
        uses: actions/upload-artifact@v2
        with:
          name: tap-sklik
          path: dist/tap-sklik-*/
